/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MlFlag {
        "defTxtSelect": string;
        "default": string;
        "flags": string;
        "label": string;
        "reset": () => Promise<void>;
        "selectItem": (key: string) => Promise<void>;
        "selectedItem": () => Promise<{
            key: string;
            text: string;
            selected: boolean;
            class: string;
        }>;
        "showAll": boolean;
        "showTextDefault": boolean;
    }
}
declare global {
    interface HTMLMlFlagElement extends Components.MlFlag, HTMLStencilElement {
    }
    var HTMLMlFlagElement: {
        prototype: HTMLMlFlagElement;
        new (): HTMLMlFlagElement;
    };
    interface HTMLElementTagNameMap {
        "ml-flag": HTMLMlFlagElement;
    }
}
declare namespace LocalJSX {
    interface MlFlag {
        "defTxtSelect"?: string;
        "default"?: string;
        "flags"?: string;
        "label"?: string;
        "onClickflag"?: (event: CustomEvent<any>) => void;
        "showAll"?: boolean;
        "showTextDefault"?: boolean;
    }
    interface IntrinsicElements {
        "ml-flag": MlFlag;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ml-flag": LocalJSX.MlFlag & JSXBase.HTMLAttributes<HTMLMlFlagElement>;
        }
    }
}
